# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: code to run, run to live
email: jeremy.r.rickard@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    A blog about running, software and beverages. Opinions expressed are my own
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jrrickard.github.io" # the base hostname & protocol for your site
twitter_username: jrrickard
github_username: jrrickard 

# Build settings
markdown: redcarpet 
